http_port 8080
visible_hostname REPLACE_PROXY_NAME

# Startup injects this from container /etc/resolv.conf.
dns_nameservers REPLACE_DNS_IP

acl agent_src src "/tmp/agent_ips.lst"
acl nw_sandbox_src src "/tmp/nw_sandbox_ips.lst"
acl agent_domains dstdomain "/opt/config/agent/domains.lst"
acl agent_host dstdomain host.containers.internal
acl agent_host_ports port "/opt/config/agent/host_ports.lst"
acl nw_sandbox_domains dstdomain REPLACE_NW_SANDBOX_DOMAINS_FILE

acl agent_nw_sandbox_host dstdomain REPLACE_SANDBOX_NAME
acl agent_nw_sandbox_port port 3000

acl SSL_ports port 443
acl Safe_ports port 80
acl Safe_ports port 443
acl CONNECT method CONNECT

http_access allow agent_src agent_nw_sandbox_host agent_nw_sandbox_port
http_access allow agent_src agent_host agent_host_ports

http_access deny !Safe_ports
http_access deny CONNECT !SSL_ports

http_access allow agent_src agent_domains
http_access allow nw_sandbox_src nw_sandbox_domains

http_access deny all

cache deny all
cache_log stdio:/dev/stderr
access_log stdio:/dev/stdout

pid_filename /tmp/squid.pid
coredump_dir /tmp
