http_port 127.0.0.1:3128 name=agent
http_port 127.0.0.1:3129 name=nw_sandbox
visible_hostname REPLACE_PROXY_NAME

# Startup injects this from container /etc/resolv.conf.
dns_nameservers REPLACE_DNS_IP

acl from_agent myportname agent
acl from_nw_sandbox myportname nw_sandbox
acl agent_domains dstdomain "/opt/config/agent/domains.lst"
acl agent_host dstdomain host.containers.internal
acl agent_host_ports port "/opt/config/agent/host_ports.lst"
acl nw_sandbox_domains dstdomain REPLACE_NW_SANDBOX_DOMAINS_FILE

acl SSL_ports port 443
acl Safe_ports port 80
acl Safe_ports port 443
acl CONNECT method CONNECT

http_access allow from_agent agent_host agent_host_ports
http_access deny !Safe_ports
http_access deny CONNECT !SSL_ports
http_access allow from_agent agent_domains Safe_ports
http_access allow from_nw_sandbox nw_sandbox_domains Safe_ports

http_access deny all

cache deny all
cache_log stdio:/dev/stderr
access_log stdio:/dev/stdout

pid_filename /tmp/squid.pid
coredump_dir /tmp
