FROM archlinux

ARG USERNAME=gemini
ARG UID=1000
ARG GID=1000

COPY config/cli_packages /tmp/cli_packages

RUN pacman -Syu --noconfirm --needed zsh $(sed -e 's/#.*$//' -e '/^[[:space:]]*$/d' /tmp/cli_packages) \
    && npm install -g @google/gemini-cli@latest \
    && groupadd -g $GID $USERNAME \
    && useradd -m -u $UID -g $GID -s /bin/bash $USERNAME \
    && chsh -s /bin/zsh $USERNAME \
    && pacman -Scc --noconfirm

USER $USERNAME
WORKDIR /home/$USERNAME/workspace
CMD ["gemini"]
