FROM node:24.17-trixie-slim

ARG USERNAME=user
ARG UID=1000
ARG GID=1000

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       zsh \
       ca-certificates \
       curl \
       build-essential \
       pkg-config \
       git \
       less \
       procps \
       jq \
       socat \
       python3 \
       python3-pip \
       python3-venv \
       ripgrep \
       bubblewrap strace

RUN apt-get clean && rm -rf /var/lib/apt/lists/*

RUN userdel node && if getent group $GID; then \
         group_name=$(getent group $GID | cut -d: -f1); \
         useradd -m -u $UID -g $GID -s /bin/bash $USERNAME; \
       else \
         groupadd -g $GID $USERNAME && \
         useradd -m -u $UID -g $GID -s /bin/bash $USERNAME; \
       fi \
    && chsh -s /bin/zsh $USERNAME

ADD https://registry.npmjs.org/@openai/codex/latest /tmp/npm-codex.json
ADD https://registry.npmjs.org/@earendil-works/pi-coding-agent /tmp/npm-pi.json
ADD https://registry.npmjs.org/@anthropic-ai/claude-code /tmp/npm-claude.json

RUN npm install -g @openai/codex@latest \
    && npm install -g @earendil-works/pi-coding-agent \
    && npm install -g @anthropic-ai/claude-code

USER $USERNAME
WORKDIR /home/$USERNAME/workspace
CMD ["zsh"]
