FROM debian:trixie-slim

ARG USERNAME=user
ARG UID=1000
ARG GID=1000

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       zsh \
       ca-certificates \
       npm \
       curl \
       build-essential \
       pkg-config \
       git \
       less \
       jq \
       python3 \
       python3-pip \
       python3-venv \
       ripgrep \
    && npm install -g @google/gemini-cli@latest \
    && if getent group $GID; then \
         group_name=$(getent group $GID | cut -d: -f1); \
         useradd -m -u $UID -g $GID -s /bin/bash $USERNAME; \
       else \
         groupadd -g $GID $USERNAME && \
         useradd -m -u $UID -g $GID -s /bin/bash $USERNAME; \
       fi \
    && chsh -s /bin/zsh $USERNAME \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

USER $USERNAME
WORKDIR /home/$USERNAME/workspace
CMD ["gemini"]
