# ==========================================
# POD 1: THE PROXY
# ==========================================
apiVersion: v1
kind: Pod
metadata:
  name: proxy-pod
  labels:
    app: proxy
spec:
  containers:
  - name: proxy
    image: docker.io/ubuntu/squid:latest
    # Run our new startup script
    command: ["/bin/sh", "/opt/proxy/startup.sh"]
    
    volumeMounts:
    - name: proxy-dir
      mountPath: /opt/proxy
      
    ports:
    - containerPort: 8080
      hostPort: 5050

  volumes:
  - name: proxy-dir
    hostPath:
      path: PROJECT_ROOT/proxy
      type: Directory

---
# ==========================================
# POD 2: THE SANDBOX
# ==========================================
apiVersion: v1
kind: Pod
metadata:
  name: sandbox-pod
  labels:
    app: sandbox
spec:
  containers:
  # 1. Jailer
  - name: sandbox-node
    image: alpine:latest
    securityContext:
      capabilities:
        add: ["NET_ADMIN"]
    volumeMounts:
    - name: scripts-dir
      mountPath: /opt/scripts
    command: ["/bin/sh", "/opt/scripts/jail_sandbox.sh"]

  # 2. App
  - name: sandbox-app
    image: alpine:latest
    command: ["sleep", "infinity"]

  volumes:
  - name: scripts-dir
    hostPath:
      # USE A PLACEHOLDER HERE
      path: PROJECT_ROOT/scripts
      type: Directory

---
# ==========================================
# POD 3: THE CLI
# ==========================================
apiVersion: v1
kind: Pod
metadata:
  name: cli-pod
  labels:
    app: cli
  annotations:
    io.podman.annotations.userns: "keep-id"
spec:
  containers:
  # 1. Jailer
  - name: cli-node
    image: alpine:latest
    securityContext:
      capabilities:
        add: ["NET_ADMIN"]
    volumeMounts:
    - name: scripts-dir
      mountPath: /opt/scripts
    command: ["/bin/sh", "/opt/scripts/jail_cli.sh"]

  # 2. App
  - name: cli-app
    image: localhost/gemini-cli:latest
    imagePullPolicy: Never
    command: ["sleep", "infinity"]
    workingDir: /home/gemini/workspace
    stdin: true
    tty: true
    volumeMounts:
    - name: gemini-config-dir
      mountPath: /home/gemini/.gemini
    - name: gemini-workspace-dir
      mountPath: /home/gemini/workspace
    env:
    - name: http_proxy
      value: "http://proxy-pod:8080"
    - name: https_proxy
      value: "http://proxy-pod:8080"
    - name: no_proxy
      value: "sandbox-pod,localhost,127.0.0.1"

  volumes:
  - name: scripts-dir
    hostPath:
      # USE A PLACEHOLDER HERE
      path: PROJECT_ROOT/scripts
      type: Directory
  - name: gemini-config-dir
    hostPath:
      path: PROJECT_ROOT/dot-gemini
      type: Directory
  - name: gemini-workspace-dir
    hostPath:
      path: PROJECT_ROOT/workspace
      type: Directory
