# ==========================================
# POD 1: THE PROXY
# ==========================================
apiVersion: v1
kind: Pod
metadata:
  name: REPLACE_PROXY_POD_NAME
  labels:
    app: proxy
spec:
  hostAliases:
  - ip: "REPLACE_CLI_IP"
    hostnames:
    - cli-pod
  - ip: "REPLACE_SANDBOX_IP"
    hostnames:
    - sandbox-pod
  containers:
  - name: proxy
    image: docker.io/ubuntu/squid:latest
    command: ["/bin/sh", "/opt/scripts/proxy_startup.sh"]
    
    volumeMounts:
    - name: config-dir
      mountPath: /opt/config
      readOnly: true
    - name: scripts-dir
      mountPath: /opt/scripts
      readOnly: true
      
    ports:
    - containerPort: 8080

  volumes:
  - name: config-dir
    hostPath:
      path: PROJECT_ROOT/config
      type: Directory
  - name: scripts-dir
    hostPath:
      path: CLADDING_ROOT/scripts
      type: Directory

---
# ==========================================
# POD 2: THE SANDBOX
# ==========================================
apiVersion: v1
kind: Pod
metadata:
  name: REPLACE_SANDBOX_POD_NAME
  labels:
    app: sandbox
  annotations:
    io.podman.annotations.userns: "keep-id"
spec:
  hostAliases:
  - ip: "REPLACE_PROXY_IP"
    hostnames:
    - proxy-pod
  initContainers:
  # 1. Jailer
  - name: sandbox-node
    image: alpine:latest
    securityContext:
      runAsUser: 0
      runAsGroup: 0
      capabilities:
        add: ["NET_ADMIN"]
    volumeMounts:
    - name: scripts-dir
      mountPath: /opt/scripts
      readOnly: true
    command: ["/bin/sh", "/opt/scripts/jail_sandbox.sh"]

  containers:
  # 2. App
  - name: sandbox-app
    image: REPLACE_SANDBOX_IMAGE
    imagePullPolicy: Never
    ports:
    - containerPort: 3000
    workingDir: /home/user/workspace
    volumeMounts:
    - name: config-dir
      mountPath: /opt/config
      readOnly: true
    - name: home-dir
      mountPath: /home/user
    - name: workspace-dir
      mountPath: /home/user/workspace
    - name: masked-cladding-dir
      mountPath: /home/user/workspace/.cladding
      readOnly: true
    - name: tools-dir
      mountPath: /opt/tools
      readOnly: true
    env:
    - name: PATH
      value: "/opt/tools/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    - name: MCP_BIND_ADDR
      value: "0.0.0.0:3000"
    - name: POLICY_FILE
      value: "/opt/config/mcp-run-policy.json"
    - name: http_proxy
      value: "http://proxy-pod:8080"
    - name: https_proxy
      value: "http://proxy-pod:8080"
    - name: no_proxy
      value: "sandbox-pod,localhost,127.0.0.1"

  volumes:
  - name: scripts-dir
    hostPath:
      path: CLADDING_ROOT/scripts
      type: Directory
  - name: config-dir
    hostPath:
      path: PROJECT_ROOT/config
      type: Directory
  - name: home-dir
    hostPath:
      path: PROJECT_ROOT/home
      type: Directory
  - name: workspace-dir
    hostPath:
      path: PROJECT_ROOT/..
      type: Directory
  - name: masked-cladding-dir
    emptyDir: {}
  - name: tools-dir
    hostPath:
      path: PROJECT_ROOT/tools
      type: Directory

---
# ==========================================
# POD 3: THE CLI
# ==========================================
apiVersion: v1
kind: Pod
metadata:
  name: REPLACE_CLI_POD_NAME
  labels:
    app: cli
  annotations:
    io.podman.annotations.userns: "keep-id"
spec:
  hostAliases:
  - ip: "REPLACE_PROXY_IP"
    hostnames:
    - proxy-pod
  - ip: "REPLACE_SANDBOX_IP"
    hostnames:
    - sandbox-pod
  initContainers:
  # 1. Jailer
  - name: cli-node
    image: alpine:latest
    securityContext:
      runAsUser: 0
      runAsGroup: 0
      capabilities:
        add: ["NET_ADMIN"]
    volumeMounts:
    - name: scripts-dir
      mountPath: /opt/scripts
      readOnly: true
    command: ["/bin/sh", "/opt/scripts/jail_cli.sh"]

  containers:
  # 2. App
  - name: cli-app
    image: REPLACE_CLI_IMAGE
    imagePullPolicy: Never
    command: ["sleep", "infinity"]
    workingDir: /home/user/workspace
    stdin: true
    tty: true
    volumeMounts:
    - name: config-dir
      mountPath: /opt/config
      readOnly: true
    - name: home-dir
      mountPath: /home/user
    - name: workspace-dir
      mountPath: /home/user/workspace
    - name: masked-cladding-dir
      mountPath: /home/user/workspace/.cladding
      readOnly: true
    - name: tools-dir
      mountPath: /opt/tools
      readOnly: true
    env:
    - name: PATH
      value: "/opt/tools/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    - name: http_proxy
      value: "http://proxy-pod:8080"
    - name: https_proxy
      value: "http://proxy-pod:8080"
    - name: no_proxy
      value: "sandbox-pod,localhost,127.0.0.1"
    - name: RUN_REMOTE_SERVER
      value: "http://sandbox-pod:3000/raw"

  volumes:
  - name: scripts-dir
    hostPath:
      path: CLADDING_ROOT/scripts
      type: Directory
  - name: config-dir
    hostPath:
      path: PROJECT_ROOT/config
      type: Directory
  - name: home-dir
    hostPath:
      path: PROJECT_ROOT/home
      type: Directory
  - name: workspace-dir
    hostPath:
      path: PROJECT_ROOT/..
      type: Directory
  - name: masked-cladding-dir
    emptyDir: {}
  - name: tools-dir
    hostPath:
      path: PROJECT_ROOT/tools
      type: Directory
