# ==========================================
# POD 1: THE PROXY
# ==========================================
apiVersion: v1
kind: Pod
metadata:
  name: proxy-pod
  labels:
    app: proxy
spec:
  hostAliases:
  - ip: "REPLACE_CLI_IP"
    hostnames:
    - cli-pod
  - ip: "REPLACE_SANDBOX_IP"
    hostnames:
    - sandbox-pod
  containers:
  - name: proxy
    image: docker.io/ubuntu/squid:latest
    command: ["/bin/sh", "/opt/scripts/proxy_startup.sh"]
    
    volumeMounts:
    - name: config-dir
      mountPath: /opt/config
      readOnly: true
    - name: scripts-dir
      mountPath: /opt/scripts
      readOnly: true
      
    ports:
    - containerPort: 8080

  volumes:
  - name: config-dir
    hostPath:
      path: PROJECT_ROOT/config
      type: Directory
  - name: scripts-dir
    hostPath:
      path: PROJECT_ROOT/scripts
      type: Directory

---
# ==========================================
# POD 2: THE SANDBOX
# ==========================================
apiVersion: v1
kind: Pod
metadata:
  name: sandbox-pod
  labels:
    app: sandbox
  annotations:
    io.podman.annotations.userns: "keep-id"
spec:
  hostAliases:
  - ip: "REPLACE_PROXY_IP"
    hostnames:
    - proxy-pod
  containers:
  # 1. Jailer
  - name: sandbox-node
    image: alpine:latest
    securityContext:
      capabilities:
        add: ["NET_ADMIN"]
    volumeMounts:
    - name: scripts-dir
      mountPath: /opt/scripts
      readOnly: true
    command: ["/bin/sh", "/opt/scripts/jail_sandbox.sh"]

  # 2. App
  - name: sandbox-app
    image: localhost/mcp-run-sandbox:latest
    imagePullPolicy: Never
    ports:
    - containerPort: 3000
    volumeMounts:
    - name: config-dir
      mountPath: /opt/config
      readOnly: true
    - name: workspace-dir
      mountPath: /home/sandbox/workspace
    env:
    - name: MCP_BIND_ADDR
      value: "0.0.0.0:3000"
    - name: POLICY_FILE
      value: "/opt/config/mcp-run-policy.json"
    - name: http_proxy
      value: "http://proxy-pod:8080"
    - name: https_proxy
      value: "http://proxy-pod:8080"
    - name: no_proxy
      value: "sandbox-pod,localhost,127.0.0.1"

  volumes:
  - name: scripts-dir
    hostPath:
      path: PROJECT_ROOT/scripts
      type: Directory
  - name: config-dir
    hostPath:
      path: PROJECT_ROOT/config
      type: Directory
  - name: workspace-dir
    hostPath:
      path: PROJECT_ROOT/workspace
      type: Directory

---
# ==========================================
# POD 3: THE CLI
# ==========================================
apiVersion: v1
kind: Pod
metadata:
  name: cli-pod
  labels:
    app: cli
  annotations:
    io.podman.annotations.userns: "keep-id"
spec:
  hostAliases:
  - ip: "REPLACE_PROXY_IP"
    hostnames:
    - proxy-pod
  - ip: "REPLACE_SANDBOX_IP"
    hostnames:
    - sandbox-pod
  containers:
  # 1. Jailer
  - name: cli-node
    image: alpine:latest
    securityContext:
      capabilities:
        add: ["NET_ADMIN"]
    volumeMounts:
    - name: scripts-dir
      mountPath: /opt/scripts
      readOnly: true
    command: ["/bin/sh", "/opt/scripts/jail_cli.sh"]

  # 2. App
  - name: cli-app
    image: localhost/gemini-cli:latest
    imagePullPolicy: Never
    command: ["sleep", "infinity"]
    workingDir: /home/gemini/workspace
    stdin: true
    tty: true
    volumeMounts:
    - name: gemini-config-dir
      mountPath: /home/gemini/.gemini
    - name: gemini-workspace-dir
      mountPath: /home/gemini/workspace
    env:
    - name: http_proxy
      value: "http://proxy-pod:8080"
    - name: https_proxy
      value: "http://proxy-pod:8080"
    - name: no_proxy
      value: "sandbox-pod,localhost,127.0.0.1"

  volumes:
  - name: scripts-dir
    hostPath:
      path: PROJECT_ROOT/scripts
      type: Directory
  - name: gemini-config-dir
    hostPath:
      path: PROJECT_ROOT/dot-gemini
      type: Directory
  - name: gemini-workspace-dir
    hostPath:
      path: PROJECT_ROOT/workspace
      type: Directory
