acl cladding_github_git_agent myportname agent
acl cladding_github_git_https proto HTTPS
acl cladding_github_git_encrypted connections_encrypted
acl cladding_github_git_url dstdomain -n github.com
acl cladding_github_git_host req_header Host -i ^github[.]com(:443)?$
acl cladding_github_git_path urlpath_regex -i ^/[^/]+/[^/]+[.]git/(info/refs|git-upload-pack|git-receive-pack)$
request_header_access Authorization deny cladding_github_git_agent cladding_github_git_https cladding_github_git_encrypted cladding_github_git_url cladding_github_git_host cladding_github_git_path
request_header_add Authorization "Basic @CLADDING_GITHUB_GIT_BASIC@" cladding_github_git_agent cladding_github_git_https cladding_github_git_encrypted cladding_github_git_url cladding_github_git_host cladding_github_git_path
