acl cladding_github_api_agent myportname agent
acl cladding_github_api_https proto HTTPS
acl cladding_github_api_encrypted connections_encrypted
acl cladding_github_api_url dstdomain -n api.github.com
acl cladding_github_api_host req_header Host -i ^api[.]github[.]com(:443)?$
request_header_access Authorization deny cladding_github_api_agent cladding_github_api_https cladding_github_api_encrypted cladding_github_api_url cladding_github_api_host
request_header_add Authorization "Bearer @CLADDING_GITHUB_API_TOKEN@" cladding_github_api_agent cladding_github_api_https cladding_github_api_encrypted cladding_github_api_url cladding_github_api_host
