FROM python:3.13-slim

COPY baffle_test_origin.py /usr/local/bin/baffle_test_origin.py
COPY www /fixtures/www
COPY server.crt /fixtures/server.crt
COPY server.key /fixtures/server.key

ENTRYPOINT ["python3", "/usr/local/bin/baffle_test_origin.py"]
